#api:
#    resource: "@ApiBundle/Controller/"
#    type:     annotation
#    prefix:   /

materials:
    type:     rest
    resource: "@ApiBundle/Controller/MaterialsController.php"

categories:
    type:     rest
    resource: "@ApiBundle/Controller/CategoriesController.php"






