<?php

namespace Api\ApiBundle\Repository;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMenu()
    {
        $qb = $this->createQueryBuilder('m');
        $query = $qb->select('m')
            ->orderBy('m.position', 'desc')
            ->getQuery();

        return $query->getResult();
    }
}
