<?php

namespace Api\ApiBundle\Repository;

/**
 * ContentRichTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRichTextRepository extends \Doctrine\ORM\EntityRepository
{
}
