<?php

namespace Api\ApiBundle\Repository;

/**
 * ContentSoundCloudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentSoundCloudRepository extends \Doctrine\ORM\EntityRepository
{
}
