<?php

namespace Api\ApiBundle\Repository;

/**
 * ContentVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
