<?php

namespace Api\ApiBundle\Repository;

/**
 * ContentImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
