<?php

namespace Api\ApiBundle\Repository;

/**
 * HomePageSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomePageSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
