<?php

namespace Api\ApiBundle\Repository;

/**
 * HomePageLayoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomePageLayoutRepository extends \Doctrine\ORM\EntityRepository
{
}
