<?php

namespace Api\ApiBundle\Repository;

/**
 * RowsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RowsRepository extends \Doctrine\ORM\EntityRepository
{
}
